### ISSUE TITLE
Doesn't work :(

### ISSUE THREAD

**Issue by Gabuwu** [htr-tech/zphisher#104]
When it finish of load all the things and i run it only appears the logo and a slogan 2.1 beta, 0 options

**Comment by htr-tech** [comment]
> When it finish of load all the things and i run it only appears the logo and a slogan 2.1 beta, 0 options

its installing packages .. keep an active net connection

**Comment by Lordfamer** [comment]
Hello after finished installing commands and accepted done tried opening links but didn't and I mistakenly press the wrong botton and it kicked me out now I'm trying to login termux with the main info pls some help me give me the main name to login this zohisher so that when I click next it will direct me to the main page

**Comment by htr-tech** [comment]
> ted done tried opening links but didn't and I mistakenly press the wrong botton and it kicked me out now I'm trying to login termux with the main info pls some help me give me the main name to l

cd zphisher
bash zphisher.sg

**Comment by Lordfamer** [comment]
Thanks

**Comment by Lordfamer** [comment]
Now I click 02 Wich is Instagram and clicked negrok after initialization told me it's unable to generate link that I should try again 
How do I exit it and go back to main menu sir?

**Comment by htr-tech** [comment]
> Now I click 02 Wich is Instagram and clicked negrok after initialization told me it's unable to generate link that I should try again
> How do I exit it and go back to main menu sir?

cd zphisher
bash zphisher.sh
