### ISSUE TITLE
paypal

### ISSUE THREAD

**Issue by mudy47** [htr-tech/zphisher#149]
the pic of the paypal is not paypal its a triangle mark that say dangerous please fix it

**Comment by htr-tech** [comment]
@mudy47 thats because of your antivirus ...

page is fine 😩

**Comment by graysuit** [comment]
> 
> 
> @mudy47 thats because of your antivirus ...
> 
> page is fine 😩

Not just antivirus.
It can be because of **chrome broswer** as well.
It can be raised also when your site link starts with `https://` instead of `http://` and you don't have valid certificate.

![image](https://user-images.githubusercontent.com/54432616/108537273-41236e00-72ff-11eb-8b13-79c8f3bc7e62.png)
