### ISSUE TITLE
Ngrok link terminated after a certain timing (around half an hour)

### ISSUE THREAD

**Issue by Wind-Explorer** [htr-tech/zphisher#390]
I generated a link using ngrok successfully then I left it there for around 30 minutes. When I came back the terminal displayed "Terminated" and the link is no longer accessible. Is there any way we can prolong the lives of the links?

**Comment by htr-tech** [comment]
> I generated a link using ngrok successfully then I left it there for around 30 minutes. When I came back the terminal displayed "Terminated" and the link is no longer accessible. Is there any way we can prolong the lives of the links?

you can use ngrok premium plan ..

**Comment by czonta96** [comment]
Don't use Ngrok or Cloudflare for phishing unless you want to do it for strictly educational purpose. Since they are public server (and not yours) if the administrators notice you are actively maintaining a persistent phishing page to wait for idiots to fall on it, they will terminate your connection, and blacklist your IP.

**If you want to actually attack people with phishing you have to be a professional attacker, not a script kiddie. You have to build your own server and make it live with valid certificates and TLS 1.3 encryption.**
