### ISSUE TITLE
How to Open Victim's Password

### ISSUE THREAD

**Issue by GamerKunjappan** [htr-tech/zphisher#72]
Everything was ok. " websites/instagram/victim_ip.txt ". What to do next

**Comment by Abhsi** [comment]
You will get automatic password will he writes and click on signin but to get link you should have ngrok Sent from Mail for Windows 10 From: GamerKunjappanSent: 19 September 2020 02:09To: htr-tech/zphisherCc: SubscribedSubject: [htr-tech/zphisher] How to Open Victim's Password (#72) Everything was ok. " websites/instagram/victim_ip.txt ". What to do next—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by htr-tech** [comment]
> Everything was ok. " websites/instagram/victim_ip.txt ". What to do next

thats victim ip . that means he has clicked the link that  you have sent .. you can get a idea about his location with it ..

the victim hasn't inputted any login creds // thats why nothing appeared 😆😆😆

**Comment by anikey78** [comment]
How to clone what's app in termux

**Comment by htr-tech** [comment]
@anikey78 what ??

**Comment by anikey78** [comment]
How to use two what's app through one number?
